my_string=input("введите текст:")
length=len(my_string)
print("количество символов в введенном тексте:",length)
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(" ",""))
print(my_string[0])
print(my_string[-1])
